### ISSUE TITLE
Allow XMLResolver to run without breaking with a restrictive Java security manager

### ISSUE THREAD

**Issue by raducoravu** [xmlresolver/xmlresolver#150]
We sometimes use Saxon + XML Resolver on the server side in applications/services which have a restrictive security manager, a security manager which may no allow reading system properties, environmental variables or checking if files exist outside of a certain folder and in such cases the xml resolver may thrown errors like this one for example:

       Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Users\...tomcat\bin\bootstrap.jar" "read")
    at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
    at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
    at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
    at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
    at our.custom.CustomSecurityManager.checkRead(CustomSecurityManager.java:120)
    at java.base/java.io.File.exists(File.java:829)
    at org.xmlresolver.XMLResolverConfiguration.findClasspathCatalogFiles(XMLResolverConfiguration.java:1063)
    at org.xmlresolver.XMLResolverConfiguration.showConfig(XMLResolverConfiguration.java:796)

Ideally there would be some kind of setting to instruct the xml resolver that it should not look in system properties, env variables for more XML catalogs. Or if it looks in there, it should attempt to catch AccessControlException errors on its own and thus avoid breaking.

**Comment by ndw** [comment]
I will totally try to get out a release that addresses this problem. Just back from a long cross-country train journey, so I don't trust that my brain is functioning. I'll take a look tomorrow. If you have an environment where you can test it, could I impose upon you to try out the branch when I think I have it working?

**Comment by raducoravu** [comment]
@ndw welcome back 👍 We can try to test the changes on our side. 
I think the easiest way to go forward would be to catch AccessControlException errors when reading in your code system properties or env variables or when attempting to read or check if catalog files exist in various folder paths.
For example right now our security.policy file looks like this but we still cannot deal with situations when you are checking for XML catalogs in all folders from the entire java classpath:

          /////////////////////////////////////////////////////////////////
          // Permission for Saxon when calling XMLResolver and searching for catalogs
          permission java.io.FilePermission "${user.dir}/catalog.xml", "read";
        
        grant codeBase "file:${ope.install.dir}/lib/saxon/-" {
          // Only allow Saxon to access the XML_CATALOG and XML_RESOLVER environment variables used by XMLResolver.
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_FILES";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_CACHE";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_PREFER";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_LOGGING";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_ALLOW_PI";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_ADDITIONS";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_PARSE_RDDL";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_MERGE_HTTPS";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_CACHE_ENABLED";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_MASK_JAR_URIS";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_ALWAYS_RESOLVE";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_URI_FOR_SYSTEM";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_CACHE_UNDER_HOME";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_ARCHIVED_CATALOGS";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_CLASSPATH_CATALOGS";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_PREFER_PROPERTY_FILE";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_CATALOG_LOADER_CLASS";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_THROW_URI_EXCEPTIONS";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_RESOLVER_LOGGER_CLASS";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_ACCESS_EXTERNAL_ENTITY";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_ACCESS_EXTERNAL_DOCUMENT";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_SAX_PARSER_FACTORY_CLASS";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_DEFAULT_LOGGER_LOG_LEVEL";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_FALLBACK_LOGGER_LOG_LEVEL";
          permission java.lang.RuntimePermission "getenv.XML_CATALOG_FIX_WINDOWS_SYSTEM_IDENTIFIERS";
          permission java.lang.RuntimePermission "getenv.XMLRESOLVER_PROPERTIES";
        
          // We grant Saxon read and write permission on all properties (from the generic grant block), because
          // the catalog resolver needs to use System.getProperties()
          // but we patch the XsltModule so the properties it receives are filtered.
          permission java.util.PropertyPermission "*", "read,write";
          permission java.util.logging.LoggingPermission "control";
        };

**Comment by ndw** [comment]
Okay. I'm not really sure I grok how to lock down a run for testing. I'm guessing that the problems are mostly in the configuration where it 's looking around for things. Presumably, the catalogs you're using don't attempt to access things that aren't accessible. 

Please give the `secmgr` branch at `https://github.com/ndw/xmlresolver` a try and let me know if it's an improvement.

**Comment by raducoravu** [comment]
@ndw thanks Norm 👍 , the fixes look good, we will try them on our side and reply back.

**Comment by jlacour31** [comment]
@ndw I tested on our side with the `secmgr` branch, I got rid of all `permission java.lang.RuntimePermission "getenv.XML_CATALOG_XXX";` but still if I remove the java.class.path permission I get:
```
WARN  StageXSLT - [CH][WARN] Cannot instantiate a Configuration
java.lang.RuntimeException: Cannot instantiate a Configuration
        at net.sf.saxon.Configuration.newConfiguration(Configuration.java:277)
        at net.sf.saxon.s9api.Processor.<init>(Processor.java:83)
        at net.sf.saxon.jaxp.SaxonTransformerFactory.<init>(SaxonTransformerFactory.java:59)
        at net.sf.saxon.TransformerFactoryImpl.<init>(TransformerFactoryImpl.java:42)
        ...
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.security.AccessControlException: access denied ("java.util.PropertyPermission" "java.class.path" "read")
        at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
        at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
        at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1066)
        at java.base/java.lang.System.getProperty(System.java:829)
        at org.xmlresolver.XMLResolverConfiguration.findClasspathCatalogFiles(XMLResolverConfiguration.java:1075)
        at org.xmlresolver.XMLResolverConfiguration.showConfig(XMLResolverConfiguration.java:813)
        at org.xmlresolver.XMLResolverConfiguration.loadConfiguration(XMLResolverConfiguration.java:441)
        at org.xmlresolver.XMLResolverConfiguration.<init>(XMLResolverConfiguration.java:288)
        at net.sf.saxon.lib.CatalogResourceResolver.<init>(CatalogResourceResolver.java:46)
        at net.sf.saxon.Configuration.init(Configuration.java:475)
        at net.sf.saxon.Configuration.<init>(Configuration.java:253)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at net.sf.saxon.Configuration.newConfiguration(Configuration.java:271)
        ... 23 common frames omitted
```

**Comment by ndw** [comment]
Right. Missed a couple. Can you pull it again, please? And if there are more failures, perhaps we can discuss how I can configure my environment locally to test this. I appreciate your help, but I don't want to be a burden!

**Comment by jlacour31** [comment]
Everything seems ok right now, thank you for your prompt answer!

**Comment by ndw** [comment]
Terrific. I'll merge that in and push a new official release in a few minutes
